version: "3.8"

x-template: &template
  restart: always
  stdin_open: true
  tty: true

x-healthcheck: &healthcheck
  retries: 3
  start_period: 3s
  start_interval: 500ms
  timeout: 3s
  interval: 10s

services:
  castle-api:
    <<: *template
    build:
      context: ./services/castle-api
      dockerfile: Dockerfile
      target: development
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
    depends_on:
      nats:
        condition: service_healthy
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    volumes:
      - ./services/castle-api:/workspace

  nats:
    <<: *template
    build:
      context: ./etc/nats
      dockerfile: Dockerfile
    healthcheck:
      <<: *healthcheck
      test: ["CMD", "wget", "-qO-", "http://localhost:8222/healthz"]

  postgres:
    <<: *template
    build:
      context: ./etc/postgres
      dockerfile: Dockerfile
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASES: ${POSTGRES_DATABASES}
    shm_size: 512mb
    healthcheck:
      <<: *healthcheck
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]

  minio:
    image: docker.io/bitnami/minio:2024
    ports:
      - ${MINIO_PORT}:9000
      - ${MINIO_ADMIN_PORT}:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_DEFAULT_BUCKETS: ${MINIO_DEFAULT_BUCKETS}
    healthcheck:
      <<: *healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]

  atlas:
    <<: *template
    restart: no
    build:
      context: .
      dockerfile: ./etc/atlas/Dockerfile
    command: |
      migrate apply --env docker --dir file://services/castle-api/migrations -c file://services/castle-api/atlas.hcl
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./services:/services

  nginx:
    <<: *template
    build:
      context: ./etc/nginx
      dockerfile: Dockerfile
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - castle-api
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
