version: "3.8"

x-template: &template
  restart: always
  stdin_open: true
  tty: true

services:
  castle-api:
    <<: *template
    build:
      context: ./services/castle-api
      dockerfile: Dockerfile
      target: development
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
    depends_on:
      nats:
        condition: service_healthy
      postgres:
        condition: service_healthy
    volumes:
      - ./services/castle-api:/workspace

  nats:
    <<: *template
    build:
      context: ./etc/nats
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8222/healthz"]
      retries: 3
      start_period: 3s
      start_interval: 500ms
      timeout: 3s
      interval: 10s

  postgres:
    <<: *template
    build:
      context: ./etc/postgres
      dockerfile: Dockerfile
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASES: ${POSTGRES_DATABASES}
    shm_size: 512mb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      retries: 3
      start_period: 3s
      start_interval: 500ms
      timeout: 3s
      interval: 10s

  atlas:
    <<: *template
    restart: no
    build:
      context: .
      dockerfile: ./etc/atlas/Dockerfile
    command: |
      migrate apply --env docker --dir file://services/castle-api/migrations -c file://services/castle-api/atlas.hcl
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./services:/services

  nginx:
    <<: *template
    build:
      context: ./etc/nginx
      dockerfile: Dockerfile
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - castle-api
