version: "3.8"

x-template: &template
  restart: always
  stdin_open: true
  tty: true

services:
  castle-api:
    <<: *template
    build:
      context: ./services/castle-api
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./services/castle-api:/workspace

  nats:
    <<: *template
    build:
      context: ./etc/nats
      dockerfile: Dockerfile

  postgres:
    <<: *template
    build:
      context: ./etc/postgres
      dockerfile: Dockerfile
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASES: ${POSTGRES_DATABASES}
    shm_size: 512mb

  nginx:
    <<: *template
    build:
      context: ./etc/nginx
      dockerfile: Dockerfile
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - castle-api
