package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"
	"journeyhub/ent"
	"journeyhub/ent/schema/pulid"
	"journeyhub/graph/model"
)

// CreateRoom is the resolver for the createRoom field.
func (r *mutationResolver) CreateRoom(ctx context.Context, input model.CreateRoomInput) (*ent.Room, error) {
	panic(fmt.Errorf("not implemented: CreateRoom - createRoom"))
}

// UpdateRoom is the resolver for the updateRoom field.
func (r *mutationResolver) UpdateRoom(ctx context.Context, roomID pulid.ID, input model.UpdateRoomInput) (*ent.Room, error) {
	panic(fmt.Errorf("not implemented: UpdateRoom - updateRoom"))
}

// DeleteRoom is the resolver for the deleteRoom field.
func (r *mutationResolver) DeleteRoom(ctx context.Context, roomID pulid.ID) (*ent.Room, error) {
	panic(fmt.Errorf("not implemented: DeleteRoom - deleteRoom"))
}

// RoomChanged is the resolver for the roomChanged field.
func (r *subscriptionResolver) RoomChanged(ctx context.Context) (<-chan *ent.Message, error) {
	panic(fmt.Errorf("not implemented: RoomChanged - roomChanged"))
}
