package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"journeyhub/ent"
	"journeyhub/ent/schema/pulid"
)

// GeneratePinCode is the resolver for the generatePinCode field.
func (r *mutationResolver) GeneratePinCode(ctx context.Context) (*string, error) {
	return r.contactsService.GenerateUserPinCode(ctx)
}

// AddUserContact is the resolver for the addUserContact field.
func (r *mutationResolver) AddUserContact(ctx context.Context, pincode string) (*ent.UserContactEdge, error) {
	userContact, err := r.contactsService.AddUserContact(ctx, pincode)
	if err != nil {
		return nil, err
	}
	return userContact.ToEdge(ent.DefaultUserContactOrder), nil
}

// DeleteUserContact is the resolver for the deleteUserContact field.
func (r *mutationResolver) DeleteUserContact(ctx context.Context, userContactID pulid.ID) (*ent.UserContactEdge, error) {
	userContact, err := r.contactsService.DeleteUserContact(ctx, userContactID)
	if err != nil {
		return nil, err
	}
	return userContact.ToEdge(ent.DefaultUserContactOrder), nil
}
