package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"journeyhub/ent"
)

// GeneratePinCode is the resolver for the generatePinCode field.
func (r *mutationResolver) GeneratePinCode(ctx context.Context) (*string, error) {
	return r.contactsService.GenerateUserPinCode(ctx)
}

// AddContact is the resolver for the addContact field.
func (r *mutationResolver) AddContact(ctx context.Context, pincode string) (*ent.UserContact, error) {
	return r.contactsService.AddUserContact(ctx, pincode)
}
