package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"journeyhub/ent"
	"journeyhub/graph/model"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.UserRegisterInput) (*ent.User, error) {
	if validationErrors := r.validationService.ValidateGqlStruct(input); len(validationErrors) > 0 {
		return &ent.User{}, validationErrors
	}

	return r.authService.Register(
		ctx,
		input.FirstName,
		input.LastName,
		input.Email,
		input.Nickname,
		input.Password,
		input.PasswordConfirmation,
	)
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.UserLoginInput) (*model.LoginUser, error) {
	if validationErrors := r.validationService.ValidateGqlStruct(input); len(validationErrors) > 0 {
		return &model.LoginUser{}, validationErrors
	}

	return r.authService.Login(
		ctx,
		input.NicknameOrEmail,
		input.Password,
	)
}
