# Server configuration
server:
  host: localhost
  port: 8080

# Auth configuration
auth:
  secret: secret

# Livekit configuration
livekit:
  access_key: devkey
  secret_key: secret

# Nats configuration
nats:
  host: nats
  port: 4222

# Database configuration
database:
  host: postgres
  port: 5432
  database: castle
  user: admin
  password: "123456"
  driver: postgres

# S3 configuration
s3:
  host: minio:9000
  access_key: admin
  secret_key: "12345678"
  bucket: media
  ssl: false
