version: "3"

interval: 500ms

tasks:
  audit:
    desc: Run quality control checks
    cmds:
      - go mod verify
      - go vet ./...
      - go run honnef.co/go/tools/cmd/staticcheck@latest -checks=all,-ST1000,-U1000 ./...
      - go run golang.org/x/vuln/cmd/govulncheck@latest ./...
      - go test -race -buildvcs -vet=off ./...
    ignore_error: true

  mod:
    desc: Downloads and tidy Go modules
    cmds:
      - go mod download
      - go mod tidy
      - go mod vendor

  build:
    desc: Build the application
    cmds:
      - go build -o ./.tmp/server ./cmd/server

  run:
    desc: Run the application
    cmds:
      - ./.tmp/server

  watch:
    desc: Watch and rebuild the application
    watch: true
    sources:
      - "**/*.go"
    cmds:
      - task: build
      - task: run

  test:
    desc: Runs test suite
    cmds:
      - go test {{catLines .GO_PACKAGES}}
    vars:
      GO_PACKAGES:
        sh: go list ./...

  cleanup:
    desc: Cleanup temp data
    cmds:
      - rm -rf .task
