// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"journeyhub/ent/file"
	"journeyhub/ent/message"
	"journeyhub/ent/messageattachment"
	"journeyhub/ent/predicate"
	"journeyhub/ent/room"
	"journeyhub/ent/schema/pulid"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MessageAttachmentQuery is the builder for querying MessageAttachment entities.
type MessageAttachmentQuery struct {
	config
	ctx         *QueryContext
	order       []messageattachment.OrderOption
	inters      []Interceptor
	predicates  []predicate.MessageAttachment
	withRoom    *RoomQuery
	withMessage *MessageQuery
	withFile    *FileQuery
	withFKs     bool
	modifiers   []func(*sql.Selector)
	loadTotal   []func(context.Context, []*MessageAttachment) error
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MessageAttachmentQuery builder.
func (maq *MessageAttachmentQuery) Where(ps ...predicate.MessageAttachment) *MessageAttachmentQuery {
	maq.predicates = append(maq.predicates, ps...)
	return maq
}

// Limit the number of records to be returned by this query.
func (maq *MessageAttachmentQuery) Limit(limit int) *MessageAttachmentQuery {
	maq.ctx.Limit = &limit
	return maq
}

// Offset to start from.
func (maq *MessageAttachmentQuery) Offset(offset int) *MessageAttachmentQuery {
	maq.ctx.Offset = &offset
	return maq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (maq *MessageAttachmentQuery) Unique(unique bool) *MessageAttachmentQuery {
	maq.ctx.Unique = &unique
	return maq
}

// Order specifies how the records should be ordered.
func (maq *MessageAttachmentQuery) Order(o ...messageattachment.OrderOption) *MessageAttachmentQuery {
	maq.order = append(maq.order, o...)
	return maq
}

// QueryRoom chains the current query on the "room" edge.
func (maq *MessageAttachmentQuery) QueryRoom() *RoomQuery {
	query := (&RoomClient{config: maq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := maq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := maq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(messageattachment.Table, messageattachment.FieldID, selector),
			sqlgraph.To(room.Table, room.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, messageattachment.RoomTable, messageattachment.RoomColumn),
		)
		fromU = sqlgraph.SetNeighbors(maq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryMessage chains the current query on the "message" edge.
func (maq *MessageAttachmentQuery) QueryMessage() *MessageQuery {
	query := (&MessageClient{config: maq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := maq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := maq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(messageattachment.Table, messageattachment.FieldID, selector),
			sqlgraph.To(message.Table, message.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, messageattachment.MessageTable, messageattachment.MessageColumn),
		)
		fromU = sqlgraph.SetNeighbors(maq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryFile chains the current query on the "file" edge.
func (maq *MessageAttachmentQuery) QueryFile() *FileQuery {
	query := (&FileClient{config: maq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := maq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := maq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(messageattachment.Table, messageattachment.FieldID, selector),
			sqlgraph.To(file.Table, file.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, messageattachment.FileTable, messageattachment.FileColumn),
		)
		fromU = sqlgraph.SetNeighbors(maq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first MessageAttachment entity from the query.
// Returns a *NotFoundError when no MessageAttachment was found.
func (maq *MessageAttachmentQuery) First(ctx context.Context) (*MessageAttachment, error) {
	nodes, err := maq.Limit(1).All(setContextOp(ctx, maq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{messageattachment.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (maq *MessageAttachmentQuery) FirstX(ctx context.Context) *MessageAttachment {
	node, err := maq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MessageAttachment ID from the query.
// Returns a *NotFoundError when no MessageAttachment ID was found.
func (maq *MessageAttachmentQuery) FirstID(ctx context.Context) (id pulid.ID, err error) {
	var ids []pulid.ID
	if ids, err = maq.Limit(1).IDs(setContextOp(ctx, maq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{messageattachment.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (maq *MessageAttachmentQuery) FirstIDX(ctx context.Context) pulid.ID {
	id, err := maq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MessageAttachment entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MessageAttachment entity is found.
// Returns a *NotFoundError when no MessageAttachment entities are found.
func (maq *MessageAttachmentQuery) Only(ctx context.Context) (*MessageAttachment, error) {
	nodes, err := maq.Limit(2).All(setContextOp(ctx, maq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{messageattachment.Label}
	default:
		return nil, &NotSingularError{messageattachment.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (maq *MessageAttachmentQuery) OnlyX(ctx context.Context) *MessageAttachment {
	node, err := maq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MessageAttachment ID in the query.
// Returns a *NotSingularError when more than one MessageAttachment ID is found.
// Returns a *NotFoundError when no entities are found.
func (maq *MessageAttachmentQuery) OnlyID(ctx context.Context) (id pulid.ID, err error) {
	var ids []pulid.ID
	if ids, err = maq.Limit(2).IDs(setContextOp(ctx, maq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{messageattachment.Label}
	default:
		err = &NotSingularError{messageattachment.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (maq *MessageAttachmentQuery) OnlyIDX(ctx context.Context) pulid.ID {
	id, err := maq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MessageAttachments.
func (maq *MessageAttachmentQuery) All(ctx context.Context) ([]*MessageAttachment, error) {
	ctx = setContextOp(ctx, maq.ctx, ent.OpQueryAll)
	if err := maq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*MessageAttachment, *MessageAttachmentQuery]()
	return withInterceptors[[]*MessageAttachment](ctx, maq, qr, maq.inters)
}

// AllX is like All, but panics if an error occurs.
func (maq *MessageAttachmentQuery) AllX(ctx context.Context) []*MessageAttachment {
	nodes, err := maq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MessageAttachment IDs.
func (maq *MessageAttachmentQuery) IDs(ctx context.Context) (ids []pulid.ID, err error) {
	if maq.ctx.Unique == nil && maq.path != nil {
		maq.Unique(true)
	}
	ctx = setContextOp(ctx, maq.ctx, ent.OpQueryIDs)
	if err = maq.Select(messageattachment.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (maq *MessageAttachmentQuery) IDsX(ctx context.Context) []pulid.ID {
	ids, err := maq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (maq *MessageAttachmentQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, maq.ctx, ent.OpQueryCount)
	if err := maq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, maq, querierCount[*MessageAttachmentQuery](), maq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (maq *MessageAttachmentQuery) CountX(ctx context.Context) int {
	count, err := maq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (maq *MessageAttachmentQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, maq.ctx, ent.OpQueryExist)
	switch _, err := maq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (maq *MessageAttachmentQuery) ExistX(ctx context.Context) bool {
	exist, err := maq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MessageAttachmentQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (maq *MessageAttachmentQuery) Clone() *MessageAttachmentQuery {
	if maq == nil {
		return nil
	}
	return &MessageAttachmentQuery{
		config:      maq.config,
		ctx:         maq.ctx.Clone(),
		order:       append([]messageattachment.OrderOption{}, maq.order...),
		inters:      append([]Interceptor{}, maq.inters...),
		predicates:  append([]predicate.MessageAttachment{}, maq.predicates...),
		withRoom:    maq.withRoom.Clone(),
		withMessage: maq.withMessage.Clone(),
		withFile:    maq.withFile.Clone(),
		// clone intermediate query.
		sql:  maq.sql.Clone(),
		path: maq.path,
	}
}

// WithRoom tells the query-builder to eager-load the nodes that are connected to
// the "room" edge. The optional arguments are used to configure the query builder of the edge.
func (maq *MessageAttachmentQuery) WithRoom(opts ...func(*RoomQuery)) *MessageAttachmentQuery {
	query := (&RoomClient{config: maq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	maq.withRoom = query
	return maq
}

// WithMessage tells the query-builder to eager-load the nodes that are connected to
// the "message" edge. The optional arguments are used to configure the query builder of the edge.
func (maq *MessageAttachmentQuery) WithMessage(opts ...func(*MessageQuery)) *MessageAttachmentQuery {
	query := (&MessageClient{config: maq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	maq.withMessage = query
	return maq
}

// WithFile tells the query-builder to eager-load the nodes that are connected to
// the "file" edge. The optional arguments are used to configure the query builder of the edge.
func (maq *MessageAttachmentQuery) WithFile(opts ...func(*FileQuery)) *MessageAttachmentQuery {
	query := (&FileClient{config: maq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	maq.withFile = query
	return maq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Order uint `json:"order,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MessageAttachment.Query().
//		GroupBy(messageattachment.FieldOrder).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (maq *MessageAttachmentQuery) GroupBy(field string, fields ...string) *MessageAttachmentGroupBy {
	maq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MessageAttachmentGroupBy{build: maq}
	grbuild.flds = &maq.ctx.Fields
	grbuild.label = messageattachment.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Order uint `json:"order,omitempty"`
//	}
//
//	client.MessageAttachment.Query().
//		Select(messageattachment.FieldOrder).
//		Scan(ctx, &v)
func (maq *MessageAttachmentQuery) Select(fields ...string) *MessageAttachmentSelect {
	maq.ctx.Fields = append(maq.ctx.Fields, fields...)
	sbuild := &MessageAttachmentSelect{MessageAttachmentQuery: maq}
	sbuild.label = messageattachment.Label
	sbuild.flds, sbuild.scan = &maq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MessageAttachmentSelect configured with the given aggregations.
func (maq *MessageAttachmentQuery) Aggregate(fns ...AggregateFunc) *MessageAttachmentSelect {
	return maq.Select().Aggregate(fns...)
}

func (maq *MessageAttachmentQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range maq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, maq); err != nil {
				return err
			}
		}
	}
	for _, f := range maq.ctx.Fields {
		if !messageattachment.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if maq.path != nil {
		prev, err := maq.path(ctx)
		if err != nil {
			return err
		}
		maq.sql = prev
	}
	return nil
}

func (maq *MessageAttachmentQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MessageAttachment, error) {
	var (
		nodes       = []*MessageAttachment{}
		withFKs     = maq.withFKs
		_spec       = maq.querySpec()
		loadedTypes = [3]bool{
			maq.withRoom != nil,
			maq.withMessage != nil,
			maq.withFile != nil,
		}
	)
	if maq.withRoom != nil || maq.withMessage != nil || maq.withFile != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, messageattachment.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*MessageAttachment).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &MessageAttachment{config: maq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(maq.modifiers) > 0 {
		_spec.Modifiers = maq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, maq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := maq.withRoom; query != nil {
		if err := maq.loadRoom(ctx, query, nodes, nil,
			func(n *MessageAttachment, e *Room) { n.Edges.Room = e }); err != nil {
			return nil, err
		}
	}
	if query := maq.withMessage; query != nil {
		if err := maq.loadMessage(ctx, query, nodes, nil,
			func(n *MessageAttachment, e *Message) { n.Edges.Message = e }); err != nil {
			return nil, err
		}
	}
	if query := maq.withFile; query != nil {
		if err := maq.loadFile(ctx, query, nodes, nil,
			func(n *MessageAttachment, e *File) { n.Edges.File = e }); err != nil {
			return nil, err
		}
	}
	for i := range maq.loadTotal {
		if err := maq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (maq *MessageAttachmentQuery) loadRoom(ctx context.Context, query *RoomQuery, nodes []*MessageAttachment, init func(*MessageAttachment), assign func(*MessageAttachment, *Room)) error {
	ids := make([]pulid.ID, 0, len(nodes))
	nodeids := make(map[pulid.ID][]*MessageAttachment)
	for i := range nodes {
		if nodes[i].room_message_attachments == nil {
			continue
		}
		fk := *nodes[i].room_message_attachments
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(room.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "room_message_attachments" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (maq *MessageAttachmentQuery) loadMessage(ctx context.Context, query *MessageQuery, nodes []*MessageAttachment, init func(*MessageAttachment), assign func(*MessageAttachment, *Message)) error {
	ids := make([]pulid.ID, 0, len(nodes))
	nodeids := make(map[pulid.ID][]*MessageAttachment)
	for i := range nodes {
		if nodes[i].message_attachments == nil {
			continue
		}
		fk := *nodes[i].message_attachments
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(message.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "message_attachments" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (maq *MessageAttachmentQuery) loadFile(ctx context.Context, query *FileQuery, nodes []*MessageAttachment, init func(*MessageAttachment), assign func(*MessageAttachment, *File)) error {
	ids := make([]pulid.ID, 0, len(nodes))
	nodeids := make(map[pulid.ID][]*MessageAttachment)
	for i := range nodes {
		if nodes[i].file_message_attachment == nil {
			continue
		}
		fk := *nodes[i].file_message_attachment
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(file.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "file_message_attachment" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (maq *MessageAttachmentQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := maq.querySpec()
	if len(maq.modifiers) > 0 {
		_spec.Modifiers = maq.modifiers
	}
	_spec.Node.Columns = maq.ctx.Fields
	if len(maq.ctx.Fields) > 0 {
		_spec.Unique = maq.ctx.Unique != nil && *maq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, maq.driver, _spec)
}

func (maq *MessageAttachmentQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(messageattachment.Table, messageattachment.Columns, sqlgraph.NewFieldSpec(messageattachment.FieldID, field.TypeString))
	_spec.From = maq.sql
	if unique := maq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if maq.path != nil {
		_spec.Unique = true
	}
	if fields := maq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, messageattachment.FieldID)
		for i := range fields {
			if fields[i] != messageattachment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := maq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := maq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := maq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := maq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (maq *MessageAttachmentQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(maq.driver.Dialect())
	t1 := builder.Table(messageattachment.Table)
	columns := maq.ctx.Fields
	if len(columns) == 0 {
		columns = messageattachment.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if maq.sql != nil {
		selector = maq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if maq.ctx.Unique != nil && *maq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range maq.predicates {
		p(selector)
	}
	for _, p := range maq.order {
		p(selector)
	}
	if offset := maq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := maq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MessageAttachmentGroupBy is the group-by builder for MessageAttachment entities.
type MessageAttachmentGroupBy struct {
	selector
	build *MessageAttachmentQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (magb *MessageAttachmentGroupBy) Aggregate(fns ...AggregateFunc) *MessageAttachmentGroupBy {
	magb.fns = append(magb.fns, fns...)
	return magb
}

// Scan applies the selector query and scans the result into the given value.
func (magb *MessageAttachmentGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, magb.build.ctx, ent.OpQueryGroupBy)
	if err := magb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MessageAttachmentQuery, *MessageAttachmentGroupBy](ctx, magb.build, magb, magb.build.inters, v)
}

func (magb *MessageAttachmentGroupBy) sqlScan(ctx context.Context, root *MessageAttachmentQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(magb.fns))
	for _, fn := range magb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*magb.flds)+len(magb.fns))
		for _, f := range *magb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*magb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := magb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MessageAttachmentSelect is the builder for selecting fields of MessageAttachment entities.
type MessageAttachmentSelect struct {
	*MessageAttachmentQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (mas *MessageAttachmentSelect) Aggregate(fns ...AggregateFunc) *MessageAttachmentSelect {
	mas.fns = append(mas.fns, fns...)
	return mas
}

// Scan applies the selector query and scans the result into the given value.
func (mas *MessageAttachmentSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mas.ctx, ent.OpQuerySelect)
	if err := mas.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MessageAttachmentQuery, *MessageAttachmentSelect](ctx, mas.MessageAttachmentQuery, mas, mas.inters, v)
}

func (mas *MessageAttachmentSelect) sqlScan(ctx context.Context, root *MessageAttachmentQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(mas.fns))
	for _, fn := range mas.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*mas.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mas.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
