// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"journeyhub/ent/file"
	"journeyhub/ent/friendship"
	"journeyhub/ent/message"
	"journeyhub/ent/messageattachment"
	"journeyhub/ent/messagelink"
	"journeyhub/ent/messagevoice"
	"journeyhub/ent/room"
	"journeyhub/ent/roommember"
	"journeyhub/ent/schema/pulid"
	"journeyhub/ent/user"
)

// prefixMap maps PULID prefixes to table names.
var prefixMap = map[pulid.ID]string{
	"FI": file.Table,
	"FS": friendship.Table,
	"ME": message.Table,
	"MA": messageattachment.Table,
	"ML": messagelink.Table,
	"MV": messagevoice.Table,
	"RO": room.Table,
	"RM": roommember.Table,
	"UR": user.Table,
}

// IDToType maps a pulid.ID to the underlying table.
func IDToType(ctx context.Context, id pulid.ID) (string, error) {
	if len(id) < 2 {
		return "", fmt.Errorf("IDToType: id too short")
	}
	prefix := id[:2]
	typ := prefixMap[prefix]
	if typ == "" {
		return "", fmt.Errorf("IDToType: could not map prefix '%s' to a type", prefix)
	}
	return typ, nil
}
