# ==================================================================================== #
# BASE IMAGE
# ==================================================================================== #
FROM arigaio/atlas:0.25.0-alpine as base

COPY ./services/castle-api/migrations /migrations/castle-api
